author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Filter::LZO
name: POE-Filter-LZO
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Compress::LZO: 1.08
  POE: 0.3501
version: 1.5
