# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-LZO
version:      1.2
version_from: lib/POE/Filter/LZO.pm
installdirs:  site
requires:
    Carp:                          0
    Compress::LZO:                 1.08
    POE:                           0.3501

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
